tasklist/config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#welcome'
   devise_for :users, controllers: {
     sessions: 'users/sessions',
     passwords: 'users/passwords',
     registrations: 'users/registrations'
   }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :notebooks
  resources :tasks
end

tasklist/app/models/notebook.rb
class Notebook < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :notebooks_by_tasks, class_name: 'IntNotebookTask'
end

tasklist/app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_id = current_user
    @notebooks = Notebook.where(user_id: @user_id).all
  end

  def new
    @notebook = Notebook.new
  end

  def edit
    find_notebook
    if @notebook.nil?
      flash[:error] = "Can't find Notebook"
      redirect_to root_path
    end
  end

  def create
    @user = current_user

    @notebook = Notebook.new(notebook_params)
    @notebook.user = @user

    if @notebook.save
      flash[:success] = "Notebook created. Ok"
      redirect_to notebook_params
    else
      flash[:error] = "Notebook can't be created"
      render 'new'
    end
  end

  def destroy
    find_notebook
    if @notebook.destroy
      flash[:success] = "Notebook destroyed successfully"
    else
      flash[:error] = "Notebook can't be destroyed"
    end
    redirect_to notebook_path
  end

  def update
    find_notebook
    if @notebook.update(notebook_params)
      flash[:success] = "Notebook updated. Ok"
      redirect_to notebook_path
    else
      #flash[:error] = "Notebook can't be updated"
      render 'edit'
    end
  end

  def show
    find_notebook
    if @notebook.nil?
      flash[:error] = "Can't be find Notebook"
      redirect_to root_path
    end
  end

private

def find_notebook
  @notebook = Notebook.find_by(id: params[:id])
end

def notebook_params
  params.require(:notebook).permit(:subject, :user_id, :create_date)
end


end

tasklist/app/helpers/notebooks_helper.rb
module NotebooksHelper
end

tasklist/app/views/notebooks/_form.html.erb
<% form_name ||= "Notebooks" %>
<h1 class="text-center">  <%= form_name %> Notebook </h1>
<%= form_for @notebook , method: (form_name.downcase == 'edit' ? 'put' : 'post') do |f| %>
  <% if @notebook.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@notebook.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @notebook.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group">
    <%= f.label :subject%>
    <%= f.text_field :subject, class: "form-control" %>
  </div>
  <%= f.submit "#{form_name} Notebook", class: "btn btn-primary" %>
  <a href="<%= notebooks_path %>" class="btn btn-default"> View all </a>
<% end %>

tasklist/app/views/notebooks/edit.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

tasklist/app/views/notebooks/index.html.erb
<div class="container">
    <h1 class="text-center"> Notebooks </h1>
<div class="text-center">

  <section class="row text.center">
  <a href="<%= new_notebook_path %>" class='btn btn-primary'> New </a>
</div>


  </section>
  <% @notebooks.each do |n| %>
  <table class="table table-hover table-striped">
    <thead>
      <th>Subject</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <tr>
        <td><%= n.subject %></td>
        <td><a href="<%= notebook_path(n.id) %>" data-method="delete" class="btn btn-danger"> Delete </a></li>
        <td><a href="<%= edit_notebook_path(n.id) %>" class="btn btn-primary"> Edit </a></li>
        <td><a href="<%= notebook_path(n.id) %>" class="btn btn-info"> Show </a></li>
      </tr>
    </tbody>
  </table>
  <% end if @notebooks.any? %>
</div>

tasklist/app/views/notebooks/new.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

tasklist/app/views/notebooks/show.html.erb
<div class="container">
  <article>
    <h1 class="text-center">Task</h1>

    <table class="table table-hover table-striped">
      <thead>
        <th>Subject</th>
      </thead>
      <tbody>
        <tr>
          <td><%= @notebook.subject%></td>
        </tr>
      </tbody>
    </table>
      <div class="text-center">
        <a href="<%= notebooks_path %>" class="btn btn-info"> Back </a></li>
        <a href="<%= notebooks_path(@notebook.id) %>" data-method="delete" class="btn btn-danger"> Delete </a></li>
      </div>

    </article>
    </div>